#ifndef GUARD_CONSTANTS_SPECIES_RANDOM_H
#define GUARD_CONSTANTS_SPECIES_RANDOM_H

enum StarterRandomMode
{
    STARTER_RANDOM_ALL,
    STARTER_RANDOM_NON_LEGEND,
    STARTER_RANDOM_STARTERS_ONLY,
    STARTER_RANDOM_MODE_COUNT,
};

enum SpeciesRandomContext
{
    SPECIES_RAND_CTX_NORMAL,
    SPECIES_RAND_CTX_SKIP,
    SPECIES_RAND_CTX_FISHING,
    SPECIES_RAND_CTX_STARTER,
    SPECIES_RAND_CTX_SCRIPTED_WILD,
};

#endif // GUARD_CONSTANTS_SPECIES_RANDOM_H
